repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        name: poetry-check-backend
        args: ["-C", "./backend"]
      - id: poetry-lock
        name: poetry-lock-backend
        args: ["-C", "./backend"]
      - id: poetry-export
        name: poetry-export-backend
        args:
          [
            "-C",
            "./backend",
            "-f",
            "requirements.txt",
            "-o",
            "./backend/requirements.txt",
            "--without-hashes",
          ]
      - id: poetry-export
        name: poetry-export-backend-dev
        args:
          [
            "-C",
            "./backend",
            "-f",
            "requirements.txt",
            "-o",
            "./backend/requirements-dev.txt",
            "--without-hashes",
            "--dev"
          ]