FROM python:3.12-alpine as builder
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

FROM python:3.12-alpine as runtime
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY src /app/src
WORKDIR /app
RUN adduser -D user
USER user
ARG PORT=8080
ENV PORT=${PORT}
EXPOSE ${PORT}
CMD python -m uvicorn src.app:app --host 0.0.0.0 --port ${PORT}